### PR TITLE
Add more tests for AventusVote

### PR DESCRIPTION
**Pull request by andy-mcewan-aventus-io**
Test all good/bad cases for setting up a Proposal.

### CODE REVIEW

**Comment by andy-mcewan-aventus-io** [comment]
Second commit from my personal branch added.

**Comment by vtan8** [comment]
I like how you intuitively name the functions.   One idea: I use the following functions to help minimize creating the nearly identical functions like createProposalZZZZZZ() or finaliseProposalZZZZZZ() etc.
   
    function getLastProposalId() {
      return proposalId;
    }

    async function createProposalWithOwner(desc, owner) {
      await avtVote.createProposal(desc, {from: owner || owner1});
      ++proposalId;
    }

    async function finaliseProposalWithId(lobbyStartTime, votingPeriod, _owner, _proposalId) {
      _proposalId = _proposalId || getLastProposalId();
      lobbyStartTime = lobbyStartTime || now();
      votingPeriod = votingPeriod || minimumVotingPeriod;
      _owner = _owner || owner1;
      await avtVote.finaliseProposal(_proposalId, lobbyStartTime, votingPeriod, { from: _owner });
    }

**Comment by andy-mcewan-aventus-io** [comment]
Ooh. I didn't know you could do default values like that. That's nice :) I can't see it working with multiple defaults, though? If, say, I wanted to call your finaliseProposalWithId() but specify the proposalId and not the owner? Because there is no type checking, it wouldn't work, right?

**Comment by andy-mcewan-aventus-io** [comment]
I've updated the code to have owner optional. Seems you can only have one optional parameter, though. PTAL :)

**Comment by andy-mcewan-aventus-io** [comment]
That doesn't seem to work :( If you set option2 without option1 it breaks.

I'll submit it as it is now so you can get on with merging in what you are doing. Then we can discuss this properly next week.

**Pull request merged**
